apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-fanout-example
  annotations: {"fortiadc-ip": "10.3.0.4", "fortiadc-login": "fad-login", "fortiadc-vdom": "root", "fortiadc-ctrl-log": "enable", "virtual-server-ip": "10.3.0.4", "virtual-server-interface": "port1", "virtual-server-port": "6000", "load-balance-method": "LB_METHOD_LEAST_CONNECTION", "load-balance-profile": "LB_PROF_HTTP"}
spec:
  ingressClassName: fadc-ingress-controller
  rules:
  - host: test.com
    http:
      paths:
      - path: /info
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 1241
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 1242
